export const gallery = [
  { id: 1, label: '**Wine** bar' },
  { id: 2, label: 'Quadra de **tênis**' },
  { id: 3, label: 'Quadra **poliesportiva**' },
  { id: 4, label: 'Quadra **beach tennis**' },
  { id: 5, label: '**Piscinas** adulto e infantil' },
  { id: 6, label: '**Pet** shower' },
  { id: 7, label: '**Sauna**' },
  { id: 8, label: 'Sala de **massagem**' },
  { id: 9, label: '**Hall** de entrada' },
  { id: 10, label: 'Sala de **jogos teen**' },
  { id: 11, label: 'Sala de **jogos**' },
  { id: 12, label: '**Fitness**' },
  { id: 13, label: '**Salão de festas** gourmet' },
  { id: 14, label: '**Salão de festas** gourmet' },
  { id: 15, label: '**Salão de festas** externo' },
  { id: 16, label: '**Fachada**' },
  { id: 17, label: 'Sala de **dança**' },
  { id: 18, label: '**Bar** da piscina' },
  { id: 19, label: '**Beauty** care' },
  { id: 20, label: '**Coworking**' },
  { id: 21, label: '**Casa de campo** interna' },
  { id: 22, label: '**Pool house** externa' },
  { id: 23, label: '**Suíte** master' },
  { id: 24, label: '**Cozinha** e sala de jantar' },
  { id: 25, label: '**Living** integrado' },
  { id: 26, label: '**Living** integrado' },
  { id: 27, label: '**Living** integrado' },
];
