export const itemsLeisure = [
  { id: 1, label: 'Quadra de beach tennis' },
  { id: 2, label: 'Quadra de tênis' },
  { id: 3, label: 'Pool house' },
  { id: 4, label: 'Espaço delivery' },
  { id: 5, label: 'Piscina adulto' },
  { id: 6, label: 'Piscina infantil' },
  { id: 7, label: 'Bar da piscina' },
  { id: 8, label: 'Deck molhado' },
  { id: 9, label: 'Bicicletário' },
  { id: 10, label: 'Salões de festas gourmet' },
  { id: 11, label: 'Infraestrutura para mini-mercado' },
  { id: 12, label: 'Churrasqueira' },
  { id: 13, label: 'Wine bar' },
  { id: 14, label: 'Fitness' },
  { id: 15, label: 'Pet place' },
  { id: 16, label: 'Pet shower' },
  { id: 17, label: 'Quadra poliesportiva' },
  { id: 18, label: 'Quadra poliesportiva' },
  { id: 19, label: 'Beauty care' },
  { id: 20, label: 'Espaço massagem' },
  { id: 21, label: 'Sala de jogos adulto' },
  { id: 22, label: 'Sala de jogos teen' },
  { id: 23, label: 'Brinquedoteca' },
  { id: 24, label: 'Playground' },
  { id: 25, label: 'Coworking' },
  { id: 26, label: 'Sauna' },
  { id: 27, label: 'Pista de caminhada' },
];
